import streamlit as st
import pandas as pd
import joblib

st.title("Augmented Data Predictions")
st.subheader("Classification and Regression using Augmented Models")

st.markdown("""
This page demonstrates predictions generated by machine learning models trained on an
**augmented (synthetic) version** of the Amazon stock dataset.

The augmented dataset is derived from the original feature-engineered dataset by applying
**controlled random perturbations** to numerical features.  
The objective is **not to improve accuracy**, but to:

- Increase data diversity
- Test model robustness
- Observe how predictions behave under small feature variations
""")

st.info(
    "Augmented data simulates additional market scenarios while preserving "
    "statistical structure and feature relationships."
)

# Load augmented data
@st.cache_data
def load_augmented_data():
    return pd.read_csv(
        "/Users/farhanfahim/Documents/Assistance Systems (WS25:26)/ai-assistant-stock-trend-predictor-farhan-fahim-taimoor/Data/AMZN_augmented_data_with_features.csv"
    )

aug_df = load_augmented_data()

st.markdown("### Augmented Dataset Preview")
st.write("First 5 rows of the augmented dataset:")
st.dataframe(aug_df.head())

st.markdown("""
**How augmentation was performed:**
- Small Gaussian noise was added to selected numerical features
- Noise magnitude was kept low to avoid unrealistic values
- Temporal order, targets, and labels were preserved
- No future information was introduced (no data leakage)

This ensures the augmented data remains **realistic but slightly perturbed**.
""")

st.divider()

# Load augmented models
clf_model = joblib.load(
    "/Users/farhanfahim/Documents/Assistance Systems (WS25:26)/ai-assistant-stock-trend-predictor-farhan-fahim-taimoor/models/rf_classifier_augmented.joblib"
)
reg_1d_model = joblib.load(
    "/Users/farhanfahim/Documents/Assistance Systems (WS25:26)/ai-assistant-stock-trend-predictor-farhan-fahim-taimoor/models/rf_1day_regressor_augmented.joblib"
)
reg_5d_model = joblib.load(
    "/Users/farhanfahim/Documents/Assistance Systems (WS25:26)/ai-assistant-stock-trend-predictor-farhan-fahim-taimoor/models/rf_5day_regressor_augmented.joblib"
)

st.markdown("### Input Technical Indicators")

features = {
    "Daily_Return": st.slider("Daily Return", -0.1, 0.1, 0.0),
    "Price_Change_Pct": st.slider("Price Change %", -5.0, 5.0, 0.0),
    "Volatility": st.slider("Volatility", 0.0, 10.0, 2.0),
    "Volume_Change": st.slider("Volume Change", -1.0, 1.0, 0.0),
    "Momentum": st.slider("Momentum", -10.0, 10.0, 0.0),
    "RSI": st.slider("RSI", 0.0, 100.0, 50.0),
    "MACD": st.slider("MACD", -5.0, 5.0, 0.0),
    "MACD_Diff": st.slider("MACD Diff", -2.0, 2.0, 0.0),
    "BB_Position": st.slider("Bollinger Band Position", 0.0, 1.0, 0.5),
    "Volume_Ratio": st.slider("Volume Ratio", 0.0, 3.0, 1.0),
    "ROC": st.slider("Rate of Change", -10.0, 10.0, 0.0),
    "ATR": st.slider("ATR", 0.0, 10.0, 1.0),
}

X = pd.DataFrame([features])

st.divider()
st.header("Predictions (Augmented Models)")

col1, col2, col3 = st.columns(3)

with col1:
    if st.button("Predict Direction (Classification)"):
        pred = clf_model.predict(X)[0]
        prob = clf_model.predict_proba(X)[0]
        if pred == 1:
            st.success(f"UP 📈 ({prob[1]*100:.2f}% confidence)")
        else:
            st.error(f"DOWN 📉 ({prob[0]*100:.2f}% confidence)")

with col2:
    if st.button("Predict 1-Day Return"):
        pred_1d = reg_1d_model.predict(X)[0]
        st.success(f"Predicted 1-Day Return: {pred_1d*100:.2f}%")

with col3:
    if st.button("Predict 5-Day Return"):
        pred_5d = reg_5d_model.predict(X)[0]
        st.success(f"Predicted 5-Day Return: {pred_5d*100:.2f}%")

st.divider()

st.markdown("### How to Interpret These Predictions")

st.markdown("""
#### Classification Output
- **UP** → weak upward signal detected  
- **DOWN** → weak downward signal detected  
- Confidence near **50 percent** → high uncertainty  
- Values above **60 percent** are rare in financial markets  

#### Regression Output Scale
- Below **-1.0 percent** → strong negative expectation  
- **-0.2 to +0.2 percent** → neutral zone  
- Above **+1.0 percent** → strong positive expectation  

#### Important Notes
- Augmented data does not add new information
- It helps test model stability and sensitivity
- Similar performance to real data suggests robustness
""")

st.info(
    "These predictions are for educational and analytical purposes only. "
    "Augmented data helps evaluate robustness, not market profitability."
)